### ISSUE TITLE
Why doesn't the data change when I move items

### ISSUE THREAD

**Issue by HryYyR** [MaxLeiter/sortablejs-vue3#33]
No matter how I move the items, the array has not changed

**Comment by MaxLeiter** [comment]
Please follow the instructions in the README for using a state management library. I'll try and make them more clear, as they don't _just_ apply to vuex. https://github.com/MaxLeiter/sortablejs-vue3#vuex

**Comment by Sjoerd82** [comment]
Yeah, this confused me as well.

I too had issues with Vue3+Vue-Draggable, and so migrated to sortablejs-vue3.

It's a small bit of code to add to manually "moveItemInArray", but I wonder what the reasoning behind it is, why not mutate the array, like vue-draggable does (is it because side-effects are "bad"?)? Some clarification (a. that you must do this, and b. reason) would go a long way, thanks in advance!

**Comment by IvanSGurdian** [comment]
If I'm following the conversation correctly, this tool does not keep track of the changes made on the list? So If I have a list of items and I move the 1st item to the last position, the original array will not display this change? I have to do this change manually?

**Comment by MaxLeiter** [comment]
@Sjoerd82 the reasoning is I built this library for what I needed, and I already had a custom store and the relevant functions setup. A pull request improving the API is welcome!

**Comment by dominx99** [comment]
So If I do not use Vuex then I can't use this library?

I have use case that I use swap plugin from sortable and when I move items manually in array then it is not rendered.
